# Generated by Django 5.2.10 on 2026-08-24 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lessonresourcedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(max_length=500, upload_to='lessons/recordings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])])),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.lesson')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
