# Generated by Django 5.2.10 on 2026-08-24 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lessonrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Optional resource for this recorded session', max_length=500, null=True, upload_to='lessons/recordings/resources/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube recording link'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lessons/recordings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])]),
        ),
    ]
