# Generated by Django 5.2.10 on 2026-08-24 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lessonrecording_resource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecordingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to='lessons/recordings/resources/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lessonrecording')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
